feat: Add tests for api v2 methods
famedly/zitadel-rust-client pull request #25
Opened 2024-09-30 07:16 UTC by mzaniolo

Close: #15 , #16 , #18

2024-09-30 08:58 UTC, sirewix commented on tests/e2e.rs
> +	};
Is `list_users` returning `Err` ok? shouldn't we throw an error here?

2024-09-30 08:58 UTC, sirewix commented on tests/e2e.rs
> +		SetHumanProfile::new("John}".to_owned(), "Doe".to_owned()),
`}` typo?

2024-09-30 08:58 UTC, sirewix commented on tests/e2e.rs
> +	assert_eq!(user_count, 2);
```rust
assert_eq!(zitadel.list_users(query.clone())?.count.await, 2)
```

2024-09-30 08:58 UTC, sirewix commented on tests/e2e.rs
> +	assert_eq!(user_count, 1);
```rust
	let user_count = zitadel.list_users(query.clone())?.inspect(|user| {
		let user_name = user
			.human()
			.and_then(|u| u.profile())
			.and_then(|u| u.given_name())
			.expect("Couldn't get user's given name");
		assert_ne!(user_name, deleted_user_name);
	}).count.await;
	assert_eq!(user_count, 1);
```

2024-10-01 10:17 UTC, emgrav approved these changes

2024-10-01 15:42 UTC, sirewix approved these changes

2024-10-02 06:36 UTC, tlater-famedly requested changes

2024-10-02 06:36 UTC, tlater-famedly commented on Cargo.toml
Commit title should be prefixed with `test:`, otherwise this ends up in the release notes as a feature.

2024-10-02 06:36 UTC, tlater-famedly commented on README.md
> -Short description of the project.
Won't block the PR on this, but changes like this should really be a separate commit.

2024-10-02 06:37 UTC, tlater-famedly commented on Cargo.toml
Specifically for the commit that adds tests, of course.

2024-10-02 14:23 UTC, merged